### ISSUE TITLE
error in file convert_txt.php

### ISSUE THREAD

**Issue by rogercgui** [ABCD-DEVCOM/ABCD2#169]
the file is showing the error message

**Fatal error**: Uncaught Error: Call to undefined function mb\_detect\_order() in /ABCD2/www/htdocs/central/utilities/convert\_txt.php:148 Stack trace: #0 {main} thrown in **/ABCD2/www/htdocs/central/utilities/convert\_txt.php** on line **148**

**Comment by fho4abcd** [comment]
This is caused by a missing extension mbstring in PHP.
Coded solution: Check for a loaded extension (I will modify the code asap)
Immediate solution:
Check with phpinfo.php
![image](https://user-images.githubusercontent.com/64411779/132120114-43f21b77-3111-4fcf-917d-657125c36066.png)
Installing on Linux is by:
sudo apt install php-mbstring    # To support unicode
and uncomment a line php.ini:
extension=mbstring ; uncomment for ABCD

**Comment by fho4abcd** [comment]
Not closed yet, have to modify the code

**Comment by rogercgui** [comment]
Ooops, my bad!
I updated my computer's php to version 8 and didn't notice the extensions.

This stumble of mine served to start the Tutotiais posts on the ABCD- Community site: 
https://abcd-community.org/tutorials/how-to-install-and-enable-mbstring/

**Comment by edsz14** [comment]
Interesting, your tests with PHP8 ! Many more issues could pop up there... As we didn't test that yet.On 05 Sep 2021 16:22, Roger C Guilherme ***@***.***> wrote:
Ooops, my bad!
I updated my computer's php to version 8 and didn't notice the extensions.
This stumble of mine served to start the Tutotiais posts on the ABCD- Community site:
https://abcd-community.org/tutorials/how-to-install-and-enable-mbstring/

**Comment by rogercgui** [comment]
So far everything is working very well.  
On my Windows computer (XAMPP + PHP8): no errors, even the DublinCore base updates work perfectly.

On my linux I started testing yesterday. The only error was mine until now.

I'll keep testing. If I find another error I'll evaluate better before communicating.

Thanks Fred!
