### ISSUE TITLE
password and user id  not working  in these version not even with abcd as user id and password adm  

### ISSUE THREAD

**Issue by aldoeri** [ABCD-DEVCOM/ABCD2#328]
![image](https://user-images.githubusercontent.com/25265688/157030835-7f77efd8-f463-4edf-87d2-49de52e3fe23.png)

**Comment by btengio** [comment]
Check to see if you renamed the folder **cgi-bin_Windows** to **cgi-bin** and users have has full permissions/access rights to that folder.

**Comment by aldoeri** [comment]
> Check to see if you renamed the folder **cgi-bin_Windows** to **cgi-bin** and users have has full permissions/access rights to that folder.

no thats not the problems thanks

**Comment by aldoeri** [comment]
![SharedScreenshot2](https://user-images.githubusercontent.com/25265688/157303707-15ac53e9-9629-4a83-8bdd-9758f55c2e98.jpg)



















i did all form the beginin

**Comment by aldoeri** [comment]
> The screenshot shows that your Apache is not correct configured, or you have firewall issues
ok now i solved apache problems  and it gives me the same problem 
with right click i go to propetys an the security or what,  if its in security then what i do give  all privileges to who? as administrator or user ?

**Comment by btengio** [comment]
Give access to all users including the administrator.

**Comment by aldoeri** [comment]
> Give access to all users including the administrator.
but where ? thats where i dont know how  and i dont know where

**Comment by btengio** [comment]
Your installation folder i assume is in C:\ABCD so right click on this folder --> properties
![screenshot](https://user-images.githubusercontent.com/101169064/157466893-cfddbe70-4c60-4e59-87a7-78fc98945238.jpg)

Note: give permissions to all users (if you have multiple users)
Hopefully the screenshot helps.

**Comment by aldoeri** [comment]
ok i have corrected the security problem but i nee tho finde a file that contains ::9090 in the text it is in apache ? in abcd or in wamp 
the problem is in httpd and i havent find the file to seee wichi is the problem why i cant use 9090 if when i was in the original instaling i coudl enter its display but icant enter to central thats the problem and i coudl just installing it

**Comment by edsz14** [comment]
Please be aware that this space of GitHub is not meant to discuss specific installation problems of specific cases/users, only to work on the generic software itself. The problem you mention about using port 9090 is well documented in the ABCD-manuals, installation instructions etc. but for ad-hoc assistance please use the ISIS e-mailing list. 


     On Thursday, March 10, 2022, 03:07:07 AM GMT+1, aldoeri ***@***.***> wrote:  
 
 


ok i have corrected the security problem but i nee tho finde a file that contains ::9090 in the text it is in apache ? in abcd or in wamp
the problem is in httpd and i havent find the file to seee wichi is the problem why i cant use 9090 if when i was in the original instaling i coudl enter its display but icant enter to central thats the problem and i coudl just installing it

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
